spring:
  application:
    name: transacao-serivce

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: guest
    password: guest
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
